name: Run Login Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */3 * *" # 每3天运行一次
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2

      - name: 安装 Playwright 所需依赖
        run: |
          npx playwright install-deps

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.9"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install playwright aiofiles requests
          pip install playwright requests python-dotenv # 如果你重新使用 dotenv
          sudo apt-get update
          sudo apt-get install -y xvfb x11-utils libx11-dev

      - name: Install Playwright Browsers # 安装浏览器
        run: |
          python -m playwright install firefox --with-deps

      - name: Upload failure artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-failure-artifacts
          path: |
            failure_screenshot.png
            failure_page.html

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1280x1024x24 & # 启动虚拟显示
          sleep 3  # 等待 3 秒确保 Xvfb 启动成功
          echo "Xvfb started, running tests now"
          xvfb-run python freecloud_login_script.py

      - name: 运行登录脚本
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOST: ${{ secrets.WEBHOST }}
        run: |
          set PYTHONIOENCODING=utf8 && xvfb-run python freecloud_login_script.py
