name: Playwright Screenshot Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */3 * *" # 每三天执行一次

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb x11-utils libx11-dev x11-xserver-utils
          pip install playwright requests

      - name: Start Xvfb and run script
        run: |
          # 启动 Xvfb 虚拟显示，并添加调试输出
          Xvfb :99 -screen 0 1280x1024x24 -nolisten tcp -noreset &> xvfb.log &
          export DISPLAY=:99
          sleep 3
          cat xvfb.log  # 输出 Xvfb 日志以供分析
          xvfb-run python freecloud_login_script.py
