name: Playwright Screenshot Test

on:
  push:
    branches:
      - main # 触发条件，可以根据需要修改为你的默认分支
  schedule:
    - cron: "0 0 */3 * *" # 每三天执行一次，设定为 00:00（UTC）执行

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb x11-utils libx11-dev
          pip install playwright requests

      - name: Start Xvfb and run script
        run: |
          # Start Xvfb on display :99 with a screen size of 1280x1024 and 24-bit color depth
          Xvfb :99 -screen 0 1280x1024x24 &> xvfb.log &
          export DISPLAY=:99
          sleep 3  # Give Xvfb some time to initialize

          # Output the Xvfb log for debugging
          cat xvfb.log

          # Run the Playwright script using xvfb-run to handle virtual display
          xvfb-run python freecloud_login_script.py
